[Variables]
TotalGame=6

Gamecover1=pc.png
Appdir1=C:\Windows\explorer.exe

Gamecover2=browser.png
Appdir2=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

Gamecover3=cam.png
Appdir3=shell:appsFolder\Microsoft.WindowsCamera_8wekyb3d8bbwe!App

Gamecover4=music.png
Appdir4=shell:appsFolder\Microsoft.ZuneMusic_8wekyb3d8bbwe

Gamecover5=coding.png
Appdir5=C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\Code.exe

Gamecover6=settings.png
Appdir6=ms-settings: