[Icon1]
Meter=Image
ImageName=#@#Icon\#Gamecover1#
LeftMouseUpAction=["#Gamedir1#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(1)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild1]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 1]
Group=DropGroup
Bounds = Icon1
Disabled=1

[Icon2]
Meter=Image
ImageName=#@#Icon\#Gamecover2#
LeftMouseUpAction=["#Gamedir2#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(2)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild2]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 2]
Group=DropGroup
Bounds = Icon2
Disabled=1

[Icon3]
Meter=Image
ImageName=#@#Icon\#Gamecover3#
LeftMouseUpAction=["#Gamedir3#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(3)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild3]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 3]
Group=DropGroup
Bounds = Icon3
Disabled=1

[Icon4]
Meter=Image
ImageName=#@#Icon\#Gamecover4#
LeftMouseUpAction=["#Gamedir4#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(4)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild4]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 4]
Group=DropGroup
Bounds = Icon4
Disabled=1

[Icon5]
Meter=Image
ImageName=#@#Icon\#Gamecover5#
LeftMouseUpAction=["#Gamedir5#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(5)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild5]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 5]
Group=DropGroup
Bounds = Icon5
Disabled=1

[Icon6]
Meter=Image
ImageName=#@#Icon\#Gamecover6#
LeftMouseUpAction=["#Gamedir6#"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(6)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild6]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 6]
Group=DropGroup
Bounds = Icon6
Disabled=1